### PR TITLE
Propose a better vue processor

### PR DESCRIPTION
**Pull request by mat813**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._

## Description

Following the discussion in #1670, I patched together a processor that combines the processor from eslint-plugin-vue and the one from here.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:Arch Linux 6.2.13-zen-1-zen
- `@graphql-eslint/...`: master
- NodeJS: v20.2.0

## Checklist:

- [ ] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests and linter rules pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by B2o5T — CHANGES_REQUESTED** [review]
please add some code example in https://github.com/B2o5T/graphql-eslint/tree/master/examples/vue-code-file that fails with default graphql-eslint processor

**Comment by mat813** [comment]
The first commit makes it fail.

**Review by B2o5T — COMMENTED** [review]
I am not sure if I want to introduce another processor for a vue code files.
Also, I am not sure if it's an issue in graphql-eslint processor or in `eslint-plugin-vue`

@mat813 I have appreciated your contribution but could you create an issue in `eslint-plugin-vue` too?

**Comment by dimaMachina** [comment]
closed by https://github.com/dimaMachina/graphql-eslint/pull/2735

**Pull request closed without merging**
